image: node:latest

stages:
  - deploy

deploy:
  stage: deploy
  environment:
    name: production
    url: https://newtelco-home.netlify.com
  only:
    - master
  script:
    - npm i
    - npm run build
    - npm i -g netlify-cli
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod -m "$CI_COMMIT_REF_NAME@$CI_COMMIT_SHORT_SHA - $CI_COMMIT_MESSAGE"
