version: "3"
services:
  app:
    container_name: nt-maint-1
    restart: always
    build: ./
    ports:
      - "4001:4000"
    env_file:
      - .env
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

