name: Cypress (Chrome) Tests
on: [push, pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v1
        timeout-minutes: 10
        with:
          browser: chrome
          record: true
          group: "next-maintenance"
          build: npm run build
          start: npm start
          wait-on: http://localhost:4000
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
					SITE: http://localhost:4000
